pipeline:
  identifier: Build_captains_log_1684847614216
  name: Build captains-log
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1684847455462
        repoName: dexhorthy/captains-log
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - parallel:
                  - step:
                      identifier: dockerbuild
                      name: docker_build
                      spec:
                        image: plugins/docker
                        settings:
                          dry_run: "true"
                          repo: hello/world
                          tags: latest
                      timeout: ""
                      type: Plugin
                  - step:
                      type: Run
                      name: Run_1
                      identifier: Run_1
                      spec:
                        shell: Sh
                        command: go test ./...
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
